baseurl = "https://example.com/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false
  # singlePageSite moves pages from the main nav menu to sections on the homepage.
  # These only menu items with a url set to "/#section-name" will be displayed.
  # A collection is displayed for the menu identifier which matches contentTypeName.
  # The collection items use the "post" archetypes. 
  singlePageSite = true
  # For singlePageSites the collection is paginated but it would not make sense to 
  # paginate in the middle of a section, so a link to see more can be specified below.
  singlePageCollectionSeeMoreText = "Check out my projects!"
  singlePageCollectionSeeMoreLink = "/portfolio"

[params.twitter]
  creator = "@justinnuwin"
  site = "@justinnuwin"


[languages]
  [languages.en]
    title = "Terminal"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Terminal"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
